### ISSUE TITLE
Qltk

### ISSUE THREAD

**Issue by Ducpro375** [ElectroHeavenVN/Dragonboy-CommunityMod-Builds#1]
Ad có thể thêm chức năng quản lí tài khoản vào mod apk k?
Loại quản lí tài khoải add theo lô,dang:
Tk|mk|sv

**Comment by ElectroHeavenVN** [comment]
Chức năng này sẽ được thêm sau nhé, cảm ơn bạn đã góp ý

**Comment by Mrk4tsu** [comment]
> Chức năng này sẽ được thêm sau nhé, cảm ơn bạn đã góp ý

![hinh-meme-im-mom-hai-huoc_032614064](https://github.com/ElectroHeavenVN/Dragonboy-CommunityMod-Builds/assets/120944583/6063eb6b-4936-4094-a9e1-5dedb149a770)
