### ISSUE TITLE
Ad ơi. Link này bị chết rùi. check giúp em với

### ISSUE THREAD

**Issue by royaldragonit** [ElectroHeavenVN/Dragonboy-CommunityMod-Builds#2]
![image](https://github.com/user-attachments/assets/c46af2f6-0e28-49c8-90a9-1cb5db6873d4)

**Comment by royaldragonit** [comment]
Cái này không có source game hả ad?

**Comment by ElectroHeavenVN** [comment]
Fix link rồi nhé
